name: Angel Demo
on:
    push:
        branches: ['Development']

jobs:
    build:
        runs-on: ubuntu-latest
        container: python:3.10-slim
        steps:
            - name: Clone from Github repository
              uses: actions/checkout@v3
            - name: Install Requirements
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run Tests
              run: |
                python manage.py test    
